apiVersion: apps/v1
kind: Deployment
metadata:
  name: picloud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picloud
  template:
    metadata:
      labels:
        app: picloud
    spec:
      containers:
      - name: picloud
        image: marwenhm/picloudmahdi-web
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: picloud
spec:
  selector:
    app: picloud
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80  
      nodePort: 30080 
  type: NodePort
