apiVersion: apps/v1
kind: Deployment
metadata:
  name: picloud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picloud
  template:
    metadata:
      labels:
        app: picloud
    spec:
      containers:
      - name: picloud
        image: marwenhm/picloudmahdi-web
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: picloud
spec:
  selector:
    app: picloud
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # You can specify a node port in the range 30000-32767 or let Kubernetes auto-assign one
  type: NodePort
